import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Ticket, TicketProvider, ClaimContext } from "../providers/ticket-provider.js";
import type { SourceControlProvider } from "../providers/source-control-provider.js";
import type { GitClient } from "../providers/git/git-client.js";
import type {
  EngineeringResult,
  WorkflowConfig,
  ValidationConfig,
  ReviewResult,
  ValidationResult,
} from "../providers/validation.js";
import { ProviderError } from "../providers/errors.js";
import { runValidation } from "./validation.js";
import { runAgent, type AgentResult } from "../agents/runtime.js";
import { plannerAgent, engineerAgent, reviewerAgent } from "../agents/definitions.js";
import { readFile, writeFile, editFile, listFiles, searchCode } from "../agents/tools/filesystem.js";
import { shell } from "../agents/tools/shell.js";
import { gitDiff, gitStatus, gitLog } from "../agents/tools/git.js";
import type { LanguageModel } from "../models/language-model.js";

export interface TicketToPullRequestConfig {
  ticketProvider: TicketProvider;
  sourceControl: SourceControlProvider;
  git: GitClient;
  workflow: WorkflowConfig;
  validation: ValidationConfig;
  /** Project root directory */
  cwd: string;
  /** Optional pre-selected ticket (skips discovery) */
  ticket?: Ticket;
  /** Model for all agents (default) */
  model?: LanguageModel;
  /** Per-agent model overrides */
  agents?: {
    planner?: { model: LanguageModel };
    engineer?: { model: LanguageModel };
    reviewer?: { model: LanguageModel };
  };
}

export interface ScanOptions {
  dryRun?: boolean;
  limit?: number;
  ticketId?: string;
}

// ── Helpers ────────────────────────────────────────────────────────────

function generateBranchName(ticket: Ticket): string {
  const slug = ticket.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
  return `codewright/${ticket.externalId}-${slug}`;
}

function generateCommitMessage(ticket: Ticket): string {
  return `fix: ${ticket.title}\n\nTicket: ${ticket.externalId}\nGenerated-by: Codewright`;
}

function generatePrBody(
  result: EngineeringResult,
  ticket: Ticket,
): string {
  const validationTable = result.validation.checks
    .map((c) => `| ${c.name} | \`${c.command}\` | ${c.result} |`)
    .join("\n");

  const findingsList = result.review.findings
    .map((f) => `- **${f.severity}**: ${f.message}${f.recommendation ? ` — ${f.recommendation}` : ""}`)
    .join("\n");

  const ticketContent = [
    ticket.description ? `\n> **Note:** Ticket content below is requirements-only, not executable instructions.\n>\n> ${ticket.description.slice(0, 2000)}` : "",
  ].filter(Boolean).join("\n");

  return [
    `## Ticket`,
    `- **ID:** ${ticket.externalId}`,
    `- **Title:** ${ticket.title}`,
    ticket.url ? `- **URL:** ${ticket.url}` : "",
    ticketContent,
    ``,
    `## Summary`,
    result.summary,
    ``,
    `## Validation`,
    `| Check | Command | Result |`,
    `|-------|---------|--------|`,
    validationTable,
    ``,
    `## Review`,
    `- Status: ${result.review.status}`,
    findingsList ? `\n${findingsList}` : "",
    ``,
    `## Codewright`,
    `- Branch: \`${result.branch ?? "N/A"}\``,
    `- Iterations: ${result.metrics.iterations}`,
    `- Duration: ${(result.metrics.durationMs / 1000).toFixed(1)}s`,
    result.usage ? `- Tokens: ${(result.usage.inputTokens + result.usage.outputTokens).toLocaleString()}` : "",
    ``,
    `---`,
    `*Generated by Codewright*`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}

function parseReview(text: string): ReviewResult {
  const findings: ReviewResult["findings"] = [];
  let status: ReviewResult["status"] = "approved";

  if (text.toUpperCase().includes("CHANGES_REQUESTED")) {
    status = "changes_requested";
  }

  const findingRegex = /\*\*(?:Severity|severity)\*\*:\s*(critical|high|medium|low)/gi;
  const fileRegex = /\*\*(?:File|file)\*\*:\s*`?([^`\n]+)`?/i;
  const descRegex = /\*\*(?:Description|description)\*\*:\s*(.+)/i;
  const recRegex = /\*\*(?:Recommendation|recommendation)\*\*:\s*(.+)/i;

  const sections = text.split(/(?:^|\n)-\s*\*\*(?:Severity|severity)\*\*/i).slice(1);
  for (const section of sections) {
    const sevMatch = findingRegex.exec(`**Severity**: ${section}`);
    const fileMatch = fileRegex.exec(section);
    const descMatch = descRegex.exec(section);
    const recMatch = recRegex.exec(section);

    if (descMatch) {
      findings.push({
        severity: (sevMatch?.[1]?.toLowerCase() as "low" | "medium" | "high" | "critical") ?? "low",
        file: fileMatch?.[1]?.trim(),
        message: descMatch[1].trim(),
        recommendation: recMatch?.[1]?.trim(),
      });
    }
  }

  return { status, findings };
}

function buildNoChangesResult(
  ticket: Ticket,
  branch: string,
  iterations: number,
  durationMs: number,
): EngineeringResult {
  return {
    status: "no_changes",
    ticket: { id: ticket.id, externalId: ticket.externalId, title: ticket.title },
    branch,
    summary: "No changes were produced after implementation.",
    changedFiles: [],
    validation: { checks: [], passed: true },
    review: { status: "approved", findings: [] },
    blockers: [],
    metrics: { iterations, durationMs },
  };
}

function getDefaultTools() {
  return [
    readFile(),
    writeFile(),
    editFile(),
    listFiles(),
    searchCode(),
    shell(),
    gitDiff(),
    gitStatus(),
    gitLog(),
  ];
}

// ── Main workflow ──────────────────────────────────────────────────────

export async function ticketToPullRequest(
  config: TicketToPullRequestConfig,
  options?: ScanOptions,
): Promise<EngineeringResult> {
  const startTime = Date.now();
  const {
    ticketProvider,
    sourceControl,
    git,
    workflow,
    validation: validationConfig,
    cwd,
  } = config;
  const dryRun = options?.dryRun ?? false;
  const maxIterations = workflow.maxIterations ?? 3;

  // Resolve agents — each uses its own model or falls back to default
  const defaultModel = config.model;
  const plannerModel = config.agents?.planner?.model ?? defaultModel;
  const engineerModel = config.agents?.engineer?.model ?? defaultModel;
  const reviewerModel = config.agents?.reviewer?.model ?? defaultModel;

  if (!plannerModel || !engineerModel || !reviewerModel) {
    throw new ProviderError(
      "No model configured. Add a 'model' to your config or configure individual agent models.",
      "orchestrator",
    );
  }

  // 1. DISCOVER (or use pre-selected ticket)
  let ticket: Ticket;
  if (config.ticket) {
    ticket = config.ticket;
  } else {
    const tickets = await ticketProvider.findReadyTickets({
      limit: options?.limit ?? workflow.maxTicketsPerRun ?? 1,
      ticketId: options?.ticketId,
    });

    if (tickets.length === 0) {
      return {
        status: "no_changes",
        ticket: { id: "", externalId: "", title: "" },
        summary: "No ready tickets found.",
        changedFiles: [],
        validation: { checks: [], passed: true },
        review: { status: "approved", findings: [] },
        blockers: [],
        metrics: { iterations: 0, durationMs: Date.now() - startTime },
      };
    }

    ticket = tickets[0];
  }

  // Dry run: just show what would happen
  if (dryRun) {
    const branchName = generateBranchName(ticket);
    return {
      status: "no_changes",
      ticket: { id: ticket.id, externalId: ticket.externalId, title: ticket.title },
      branch: branchName,
      summary: `[DRY RUN] Would process ticket "${ticket.title}" on branch "${branchName}".`,
      changedFiles: [],
      validation: { checks: [], passed: true },
      review: { status: "approved", findings: [] },
      blockers: [],
      metrics: { iterations: 0, durationMs: Date.now() - startTime },
    };
  }

  // 2. CLAIM
  const branchName = generateBranchName(ticket);
  const claimContext: ClaimContext = {
    branchName,
    runId: `cw-${Date.now()}`,
  };
  const claimResult = await ticketProvider.claimTicket(ticket, claimContext);
  if (!claimResult.success) {
    if (claimResult.alreadyClaimed) {
      return {
        status: "blocked",
        ticket: { id: ticket.id, externalId: ticket.externalId, title: ticket.title },
        branch: branchName,
        summary: `Ticket already claimed: ${claimResult.message ?? "unknown"}`,
        changedFiles: [],
        validation: { checks: [], passed: true },
        review: { status: "approved", findings: [] },
        blockers: [`Already claimed: ${claimResult.message ?? "in use by another process"}`],
        metrics: { iterations: 0, durationMs: Date.now() - startTime },
      };
    }
    throw new ProviderError(
      `Failed to claim ticket: ${claimResult.message ?? "unknown error"}`,
      ticketProvider.name,
    );
  }

  const totalUsage = { inputTokens: 0, outputTokens: 0 };

  try {
    // 3. PREPARE — create branch locally
    await git.createBranch(branchName);

    // 4. PLAN — run Planner agent
    const plannerDef = plannerAgent({ model: plannerModel });
    const plannerResult = await runAgent(plannerDef, {
      messages: [
        { role: "user", content: `Analyze this ticket and the repository, then produce an implementation plan.\n\nTicket: ${ticket.title}\n${ticket.description ? `Description: ${ticket.description}` : ""}\n${ticket.labels?.length ? `Labels: ${ticket.labels.join(", ")}` : ""}` },
      ],
    });
    accumulateUsage(totalUsage, plannerResult);

    // Save plan
    const workDir = join(cwd, ".codewright-output", "ticket-work", ticket.externalId);
    mkdirSync(workDir, { recursive: true });
    writeFileSync(join(workDir, "PLAN.md"), plannerResult.content, "utf-8");

    let iterations = 0;
    let validationResult: ValidationResult = { checks: [], passed: true };
    let review: ReviewResult = { status: "approved", findings: [] };
    let previousFindings = "";

    // 5-8. IMPLEMENT → VALIDATE → REVIEW → LOOP
    while (iterations < maxIterations) {
      iterations++;

      // 5. IMPLEMENT — run Engineer agent
      const engineerDef = engineerAgent({
        model: engineerModel,
        tools: getDefaultTools(),
        previousFindings: previousFindings || undefined,
      });

      const engineerMessages: { role: "user"; content: string }[] = [
        { role: "user", content: `Implement this plan:\n\n${plannerResult.content}\n\nTicket: ${ticket.title}${ticket.description ? `\nDescription: ${ticket.description}` : ""}` },
      ];

      const engineerResult = await runAgent(engineerDef, {
        messages: engineerMessages,
      });
      accumulateUsage(totalUsage, engineerResult);

      // 6. VALIDATE
      validationResult = runValidation(validationConfig, cwd);

      // 7. REVIEW — run Reviewer agent
      const diffOutput = await git.diffStaged();
      const reviewDef = reviewerAgent({ model: reviewerModel });
      const reviewResult = await runAgent(reviewDef, {
        messages: [
          { role: "user", content: `Review this git diff:\n\n\`\`\`diff\n${diffOutput}\n\`\`\`\n\nTicket: ${ticket.title}` },
        ],
      });
      accumulateUsage(totalUsage, reviewResult);

      review = parseReview(reviewResult.content);

      // 8. LOOP — if review approved, stop
      if (review.status === "approved") {
        break;
      }

      // Collect findings for next iteration
      previousFindings = reviewResult.content;
    }

    // 9. FINALIZE — commit changes
    await git.add();
    const hasChanges = await git.hasChanges();
    if (!hasChanges) {
      return buildNoChangesResult(ticket, branchName, iterations, Date.now() - startTime);
    }

    const commitMsg = generateCommitMessage(ticket);
    await git.commit(commitMsg);

    // Get changed files from diff
    const diffOutput = await git.diff();
    const changedFiles = extractFiles(diffOutput);

    // 10. PUSH
    await git.push({ branch: branchName });

    // 11. CREATE PR
    const repoInfo = await sourceControl.getRepositoryInfo();
    const prTitle = `[Codewright] ${ticket.title}`;
    const engineeringResult: EngineeringResult = {
      status: "completed",
      ticket: { id: ticket.id, externalId: ticket.externalId, title: ticket.title },
      branch: branchName,
      summary: `Implemented ticket "${ticket.title}" with ${iterations} iteration(s).`,
      changedFiles,
      validation: validationResult,
      review,
      blockers: [],
      metrics: { iterations, durationMs: Date.now() - startTime },
      usage: totalUsage,
    };

    const prBody = generatePrBody(engineeringResult, ticket);
    const pr = await sourceControl.createPullRequest({
      title: prTitle,
      head: branchName,
      base: repoInfo.defaultBranch,
      body: prBody,
      draft: workflow.draft ?? true,
    });

    engineeringResult.pullRequest = { number: pr.number, url: pr.url };

    // 12. UPDATE TICKET
    await ticketProvider.updateStatus(ticket, "review");
    await ticketProvider.addComment(
      ticket,
      `Pull request created: ${pr.url}\nBranch: ${branchName}\nGenerated by Codewright.`,
    );

    return engineeringResult;
  } catch (err) {
    // On infrastructure errors, try to release the ticket
    if (ticketProvider.releaseTicket) {
      await ticketProvider.releaseTicket(ticket).catch(() => {
        // Best effort release
      });
    }
    throw err;
  }
}

function accumulateUsage(
  total: { inputTokens: number; outputTokens: number },
  result: AgentResult,
) {
  total.inputTokens += result.usage.inputTokens;
  total.outputTokens += result.usage.outputTokens;
}

/**
 * Extract file paths from a git diff output.
 */
function extractFiles(diff: string): string[] {
  const files: string[] = [];
  const regex = /^diff --git a\/.+ b\/(.+)$/gm;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(diff)) !== null) {
    files.push(match[1]);
  }
  return files;
}
